### ISSUE TITLE
Proposal: also ignore images?

### ISSUE THREAD

**Issue by starpit** [lgandecki/babel-plugin-ignore-html-and-css-imports#2]
What do you think about also ignoring .png, etc. files?

**Comment by lgandecki** [comment]
why not? :) Do you want to create a PR?

**Comment by starpit** [comment]
sure thing. thanks

**Comment by lgandecki** [comment]
once I merge that PR in I should refresh the repository a bit before a release, remove the lib folder, and add semantic-release so it releases automatically :) 
The repo is a bit stale, but I'm glad you find this small piece of code useful!

**Comment by starpit** [comment]
most certainly, thanks!

**Comment by lgandecki** [comment]
Hey @myan9 @starpit I released a new version in which you can configurable extensions of files to be removed from imports, I think this is a bit better than trying to decide what should be removed in a hardcoded way. This also allows us to keep this tiny package backward-compatible.

Please let me know if this works the way you imagined. I'm curious about your use-case with images, won't thing break anyway since now you will have not defined variables?
